sw_js = (
    "// Droidify Service Worker\n"
    "// NO fetch listener — intentional.\n"
    "// Safari 17+ WebKit bug (bugs.webkit.org/261767): any fetch\n"
    "// listener that calls event.respondWith() causes\n"
    "// 'TypeError: Load failed' blocking the entire page load.\n"
    "// Droidify has no cache and no offline mode.\n"
    "// Without a fetch listener the browser handles all requests natively.\n"
    "// This SW exists for: PWA installability, Background Sync, Periodic Sync.\n\n"
    "self.addEventListener('install', () => self.skipWaiting());\n\n"
    "self.addEventListener('activate', e => e.waitUntil(\n"
    "  caches.keys()\n"
    "    .then(keys => Promise.all(keys.map(k => caches.delete(k))))\n"
    "    .then(() => self.clients.claim())\n"
    "));\n\n"
    "// Background Sync — notify clients to retry last search when back online\n"
    "self.addEventListener('sync', event => {\n"
    "  if (event.tag === 'droidify-search-sync') {\n"
    "    event.waitUntil(\n"
    "      self.clients.matchAll({ type: 'window' })\n"
    "        .then(clients => clients.forEach(c =>\n"
    "          c.postMessage({ type: 'SYNC_COMPLETE' })\n"
    "        ))\n"
    "    );\n"
    "  }\n"
    "});\n\n"
    "// Periodic Background Sync — warm the server cache once a day\n"
    "self.addEventListener('periodicsync', event => {\n"
    "  if (event.tag === 'droidify-refresh') {\n"
    "    event.waitUntil(Promise.all([\n"
    "      fetch('/api/devices?limit=1').catch(() => {}),\n"
    "      fetch('/api/roms?limit=1').catch(() => {}),\n"
    "    ]));\n"
    "  }\n"
    "});\n\n"
    "self.addEventListener('message', event => {\n"
    "  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();\n"
    "});\n"
)

robots_txt = "User-agent: *\nAllow: /\nSitemap: /sitemap.xml\n"
