// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: devices.sql

package database

import (
	"context"
)

const getDevice = `-- name: GetDevice :one
select id, model, twrp, stock_firmware, odin, orange_fox_recovery, custom_firmeware, shrp_recovery from devices where model = $1
`

func (q *Queries) GetDevice(ctx context.Context, model string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, model)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Twrp,
		&i.StockFirmware,
		&i.Odin,
		&i.OrangeFoxRecovery,
		&i.CustomFirmeware,
		&i.ShrpRecovery,
	)
	return i, err
}
