// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Device struct {
	ID                string
	Model             string
	Twrp              sql.NullString
	StockFirmware     sql.NullString
	Odin              sql.NullString
	OrangeFoxRecovery sql.NullString
	CustomFirmeware   sql.NullString
	ShrpRecovery      sql.NullString
}
